title: ⏰ HCI Conference Deadlines for HHN
description: Countdowns to top HCI conference deadlines
author: Ahmad Alismail

domain: 'hci-deadlines-hhn.github.io'
baseurl: ''


github_username: hci-deadlines-hhn
github_repo_confdatabase: conf-database-hhn

markdown: kramdown
ga_id:

include: ['_pages']
